core/urls.py
from django.urls import path
from .views import (
    CategoryView,
    HomeView,
    ProductView,
)

app_name = 'core'

urlpatterns = [
    path('',HomeView.as_view(),name='HomeView'),
    path('product/<pk>/',ProductView.as_view(),name='ProductView'),
    path('category/<slug:category>/',CategoryView.as_view(),name='CategoryView')
]

khan_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
import notifications.urls

urlpatterns = [
    path('', include('core.urls',namespace='core')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('shop/', include('shop.urls')),
    path('auth/', include('user.urls')),
    path('admin/', admin.site.urls),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import (
    AddProductView,
    add_to_cart,
    manage_quantity,
    order_summary,
    # CreateCheckoutSessionView,
    StripeIntentView,
    payment_summary,
    stripe_webhook,
)

app_name = 'shop'

urlpatterns = [
    path('add_product/',AddProductView.as_view(),name='AddProductView'),
    path('add_to_cart/<pk>/',add_to_cart,name='add_to_cart'),
    path('order_summary/',order_summary.as_view(),name='order_summary'),
    path('manage_quantity/<slug:action>/<pk>/',manage_quantity,name='manage_quantity'),
    path('create-payment-intent/', StripeIntentView.as_view(), name='create-payment-intent'),
    path('payment_summary/', payment_summary.as_view(), name='payment_summary'),
    # path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
]
# C:\Users\Aneeq-PC\Downloads\Compressed\stripe_1.6.1_windows_x86_64\stripe.exe listen --forward-to localhost:8000/shop/webhooks/stripe/

user/urls.py
from django.urls import path,include
from django.conf.urls import url
from .views import (
    SignUpView,
    LogoutView,
    LoginView,
    AddAddressView,
    DetailUserView,
)

app_name = 'user'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="SignUpView"),
    path("login/", LoginView.as_view(), name="LoginView"),
    path("logout/", LogoutView.as_view(), name="LogoutView"),
    path("add_address/", AddAddressView.as_view(), name="AddAddressView"),
    path("details/<pk>/", DetailUserView.as_view(), name="DetailUserView"),
]

shop/models.py
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from .choices import (CATEGORIES,LABEL)
from django.core.exceptions import ObjectDoesNotExist
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your models here.

def get_upload_path(instance, filename):
    model = instance.album.model.__class__._meta
    name = model.verbose_name_plural.replace(' ', '_')
    return f'{name}/images/{filename}'

class ImageAlbum(models.Model):
    def __str__(self):
        try:
            return self.model.name + ' (Album)'
        except ObjectDoesNotExist:
            return '--' + f"({self.pk})"
    def default(self):
        return self.images.filter(default=True).first()
    def thumbnails(self):
        return self.images.filter(width__lt=100, length_lt=100)

class Image(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to=get_upload_path)
    default = models.BooleanField(default=False)
    width = models.FloatField(default=100)
    length = models.FloatField(default=100)
    album = models.ForeignKey(ImageAlbum, related_name='images', on_delete=models.CASCADE)

    def __str__(self):
        return f"Image for {self.album.model.name}({self.album.model.pk})"

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=255)
    price = models.FloatField()
    discount_price = models.FloatField(null=True,blank=True)
    category = models.CharField(choices=CATEGORIES,max_length=2)
    label = models.CharField(choices=LABEL,max_length=2,default='N')
    description = models.TextField()
    created_on = models.DateField(auto_now=True)
    album = models.OneToOneField(ImageAlbum, related_name='model', on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('core:ProductView', kwargs={
            'pk': self.pk
        })

    def get_add_to_cart_url(self):
        return reverse('shop:add_to_cart', kwargs={
            'pk': self.pk
        })
        
    def get_remove_from_cart_url(self):
        return reverse("shop:remove_from_cart", kwargs={
            "pk": self.pk
        })


# ::::::::::::::::::::::::Payment Models:::::::::::::::::::::::::: #

class Orderitem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} Piece(s) of {self.product.name}"

    def get_total_item_price(self):
        return self.quantity * self.product.price

    def get_discount_item_percentage(self):
        if self.product.discount_price is not None:
            percentage = (self.get_amount_saved() / self.get_total_item_price()) * 100
            return round(percentage,2)
        return 0

    def get_discount_item_price(self):
        if self.product.discount_price is not None:
            return self.quantity * self.product.discount_price
        return self.quantity * self.product.price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_discount_item_price()

    def get_final_price(self):
        if self.product.discount_price:
            return self.get_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='order')
    products = models.ManyToManyField(Orderitem)
    start_date = models.DateField(auto_now_add=True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)

    def __str__(self,*args, **kwargs):
        return f'{self.user.username} {self.start_date}'

    def get_count(self,*args, **kwargs):
        count = 0
        if self.products.all().count() > 0 and not self.ordered:
            count = self.products.all().count()
        print(count)
        return count
        
    def get_total_price(self,*args, **kwargs):
        total = 0
        for order_item in self.products.all():
            total += order_item.get_final_price()
        return round(total)

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,blank=True,null=True,related_name='payments')
    stripe_charge = models.CharField(max_length=50)
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)
    ammount = models.FloatField()

    def __str__(self,*args, **kwargs):
        return f'{self.user.username} ({self.ammount}$)'

    def amount_in_dollars(self, now=None):
        return self.ammount / 100
        
    def timesince(self, now=None):
        from django.utils.timesince import timesince as timesince_
        return timesince_(self.timestamp, now)

    def retrieve_reciept_url(self,*args, **kwargs):
        payment_intent = stripe.PaymentIntent.retrieve(self.stripe_charge)
        return payment_intent['charges']['data'][0]['receipt_url']
        

user/models.py
import os
from django.db.models.signals import pre_save,post_save
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
from django.dispatch.dispatcher import receiver
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
# def get_upload_path(instance, filename):
#     return os.path.join('uploads', "user_%d" % instance.user.id, filename)

PROVINCES = (
    ('S','Sindh'),
    ('P','Punjab'),
    ('B','Balochistan'),
    ('K','Khyber PakhtunKhwa'),
    ('A','Azad Kashmir'),
)


def path_and_rename(instance, filename):
    ext = filename.split('.')[-1]
    user_id = "user_%d" % instance.user.id
    # set filename as random string
    random_id = "rid_%s" % (uuid4().hex,)
    filename = '{}.u{}.{}'.format(random_id,instance.user.id, ext)
    # return the whole path to the file
    return os.path.join('uploads', user_id, filename)

class Address(models.Model):
    country = CountryField(multiple=False,blank=False,max_length=3)
    province = models.CharField(max_length=3,choices=PROVINCES,blank=False)
    city = models.CharField(max_length=200,blank=False)
    street_address = models.CharField(max_length=100,blank=True)
    zip = models.CharField(max_length=100,blank=True)

class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, null=True)
    profile_pic = models.ImageField(upload_to=path_and_rename, height_field=None, width_field=None,null=True)
    about_me = models.TextField(blank=True,null=True)
    mobile_number = PhoneNumberField()
    address = models.OneToOneField(Address, related_name='profile',null=True, blank=True,on_delete=models.SET_NULL)
    stripe_customer_id = models.CharField(max_length=100,default=None,null=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User, dispatch_uid="Create-User-Profile")
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    # post_save provides 'created' arg and pre_save don't

templates/add_product.html
{%extends 'base.html'%} {%load static%} {%block extraCSS%}
<link rel="stylesheet" href="{%static 'css/product.css'%}" />
<link rel="stylesheet" href="{%static 'css/add_product.css'%}" />
{%endblock%} {%block body%}
{%if request.user.profile.address is null%}
  <div id="add_product_address_form_cont">
    <div id="add_product_address_form">
      <a href="{%url 'core:HomeView'%}" id="add_product_address_form_back"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>
      <p id="add_product_address_form_required">You have to fill Address field in order to Post A Product</p>
      <a href="{%url 'user:AddAddressView'%}" class="a_no_style" id="add_product_address_form_a">Add Address To You Account?</a>
    </div>
  </div>
{%endif%}
<div id="product_container">
  <form action="." method="post" enctype="multipart/form-data">
    <h2>Add Product</h2>
    {%if messages%} 
    {%for message in messages%}
      <p style="color: red">{{message}}</p>
    {%endfor%} 
    {%endif%}

    {%csrf_token%}
    {%for field in form%}
      <p>{{field.label}}</p>
      <p class="help_text">{{field.help_text}}</p>
      {%for error in field.errors%}
        <p class="error">
          {{error}} <i class="fa fa-exclamation" aria-hidden="true"></i>
        </p>
      {%endfor%} 
      {{field}}
    {%endfor%}
    <p>Upload Images</p>
    <div id="image_upload_cont" class="no_scroll">
      <div class="preview preview_main">
        <label for="files"
          ><i class="fa fa-camera" aria-hidden="true"></i>
          <p>AddPhoto</p>
        </label>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
      <div class="preview preview_fade">
        <i class="fa fa-camera" aria-hidden="true"></i>
      </div>
    </div>
    <input
      style="display: none"
      name="images_files"
      id="files"
      type="file"
      accept="image/*"
      multiple
      onchange="previewFiles(event)"
    />
    <input type="submit" value="Submit" />
    <!-- <p>Don't Have an account? <a href="{%url 'user:SignUpView'%}">Create One</a></p> -->
  </form>
</div>
{%endblock%} {%block extraJS%}
<script src="{%static 'js/add_product.js'%}"></script>
{%endblock%}

templates/base.html
{%load static%}
{% load notifications_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Khan Store</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{%static 'css/base.css'%}" />
    <link rel="stylesheet" href="{%static 'css/responsive.css'%}" />

    {%block extraCSS%}
    {%endblock%}

  </head>
  <body class="body_scroll">
    <!-- Nav -->
    <nav id="main__nav">
      <div id="nav__left">
        <span id="nav__logo">
          <a href="{%url 'core:HomeView'%}" class="a_no_style">KST</a>
        </span>
        <div id="locaton_box" class="input_hover">
          <i class="fa fa-search" aria-hidden="true"></i>
          <input
            type="search"
            name="locaton_input"
            id="locaton_input"
            placeholder="Search City"
          />
        </div>
      </div>
      <div id="nav__middle">
        <div id="search_product_container" class="input_hover">
          <input
            type="search"
            name="search_product"
            id="search_product"
            placeholder="Find Products"
          />
          <div class="search_product_icon">
            <i class="fa fa-search" aria-hidden="true"></i>
          </div>
        </div>
      </div>

      <div id="nav__right__collapse__btn">
        <i class="fa fa-bars" aria-hidden="true"></i>
      </div>

      <div id="nav__right__collapse__body" style="display: none;">
          <div id="nav__right__collapse">
            {%if request.user.is_authenticated%}
            <i class="fa fa-comment-o" aria-hidden="true"></i>
            <a href="{%url 'shop:order_summary'%}" class="a_no_style">
              <i class="fa fa-shopping-cart" aria-hidden="true"></i>
              {%if request.user.order.last.get_count%}
                <p class="show_count"><span>{{request.user.order.last.get_count}}</span></p>
              {%else%}
                <p class="show_count"><span>0</span></p>
              {%endif%}
            </a>
            <div id='notification_cont_mobile' tabindex="0" style='position:relative'>
              <i class="fa fa-bell-o"  aria-hidden="true"></i>
              <p class="show_count"><span>{% live_notify_badge %}</span></p>
    
              <div id='notification_drop_mobile' style="display: none;" class="custom_sroll">
                <div class="nav__drop__details__options notification_drop_options">
                  
                </div>
              </div>
            </div>
            {%endif%}
    
            <div id="nav__avatar__cont__mobile" tabindex='0'>
              {%if request.user.is_authenticated%}
                {{ request.user.username|json_script:"req_username" }}
    
                  {%if request.user.profile.profile_pic%}
                  <div class="avatar" style="background-image:url({{request.user.profile.profile_pic.url}})"></div>
                  {%else%}
                  <div class="avatar no_profile_pic"><span></span></div>
                  {%endif%}
                  <i class="fa fa-angle-down fa-rotate-180" aria-hidden="true"></i>
                
                <div id="nav__avatar__drop__mobile" style="display: none;">
                  <div id="nav__avatar__drop__details">
                    {%if request.user.profile.profile_pic%}
                      <div class="avatar" style="background-image:url({{request.user.profile.profile_pic.url}})"></div>
                    {%else%}
                      <div class="avatar no_profile_pic" ><span></span></div>
                    {%endif%}
                    <div id="nav__avatar__drop__details__text">
                      <p id="nav__avatar__drop__hello">Hello,</p>
                      <p id="nav__avatar__drop__name">{{request.user.username}}</p>
                    </div>
                  </div>
                  <hr>
                  <div class="nav__drop__details__options">
                    <div class="nav__drop__details__option__cont">
                      <form action="{%url 'user:LogoutView'%}" method="post">
                        {%csrf_token%}
                        <i class="fa fa-sign-out nav__drop__details__option__icon" aria-hidden="true"></i>
                        <input class="nav__drop__details__option" type="Submit" value='LogOut'>
                      </form>
                    </div>
                    <div class="nav__drop__details__option__cont">
                      <i class="fa fa-sign-out nav__drop__details__option__icon" aria-hidden="true"></i>
                      <a href="{%url 'user:DetailUserView' pk=request.user.pk%}" class="nav__drop__details__option">
                        View Account Info
                      </a>
                    </div>
                  </div>
                </div>
                {%else%}
                <button id="nav__btn_login" class='nav__btn' type="button">
                  <a href="{%url 'user:LoginView'%}" class="a_no_style">
                    <span>
                      <!-- <i class="fa fa-plus" aria-hidden="true"></i> -->
                      Login
                    </span>
                  </a>
                </button>   
                {%endif%}
            </div>  
            <!-- <div id="nav__btn_sell">SELL</div> -->
            <button id="nav__btn_sell" type="button" class='nav__btn'>
                <a href="{%url 'shop:AddProductView'%}" class="a_no_style">
                  <span>
                    <i class="fa fa-plus" aria-hidden="true"></i>
                    <p>SELL</p>
                  </span>
                </a>
            </button>
          </div>    
      </div>
      

      <div id="nav__right">
        {%if request.user.is_authenticated%}
        <i class="fa fa-comment-o" aria-hidden="true"></i>
        <a href="{%url 'shop:order_summary'%}" class="a_no_style">
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          {%if request.user.order.last.get_count%}
            <p class="show_count"><span>{{request.user.order.last.get_count}}</span></p>
          {%else%}
            <p class="show_count"><span>0</span></p>
          {%endif%}
        </a>
        <div id='notification_cont' tabindex="0" style='position:relative'>
          <i class="fa fa-bell-o"  aria-hidden="true"></i>
          <p class="show_count"><span>{% live_notify_badge %}</span></p>

          <div id='notification_drop' style="display: none;" class="custom_sroll">
            <div class="nav__drop__details__options notification_drop_options">
              
            </div>
          </div>
        </div>
        {%endif%}

        <div id="nav__avatar__cont" tabindex='0'>
          {%if request.user.is_authenticated%}
            {{ request.user.username|json_script:"req_username" }}

              {%if request.user.profile.profile_pic%}
              <div class="avatar" style="background-image:url({{request.user.profile.profile_pic.url}})"></div>
              {%else%}
              <div class="avatar no_profile_pic"><span></span></div>
              {%endif%}
              <i class="fa fa-angle-down fa-rotate-180" aria-hidden="true"></i>
            
            <div id="nav__avatar__drop" style="display: none;">
              <div id="nav__avatar__drop__details">
                {%if request.user.profile.profile_pic%}
                  <div class="avatar" style="background-image:url({{request.user.profile.profile_pic.url}})"></div>
                {%else%}
                  <div class="avatar no_profile_pic" ><span></span></div>
                {%endif%}
                <div id="nav__avatar__drop__details__text">
                  <p id="nav__avatar__drop__hello">Hello,</p>
                  <p id="nav__avatar__drop__name">{{request.user.username}}</p>
                </div>
              </div>
              <hr>
              <div class="nav__drop__details__options">
                <div class="nav__drop__details__option__cont">
                  <form action="{%url 'user:LogoutView'%}" method="post">
                    {%csrf_token%}
                    <i class="fa fa-sign-out nav__drop__details__option__icon" aria-hidden="true"></i>
                    <input class="nav__drop__details__option" type="Submit" value='LogOut'>
                  </form>
                </div>
                <div class="nav__drop__details__option__cont">
                  <i class="fa fa-sign-out nav__drop__details__option__icon" aria-hidden="true"></i>
                  <a href="{%url 'user:DetailUserView' pk=request.user.pk%}" class="nav__drop__details__option">
                    View Account Info
                  </a>
                </div>
              </div>
            </div>
            {%else%}
            <button id="nav__btn_login" class='nav__btn' type="button">
              <a href="{%url 'user:LoginView'%}" class="a_no_style">
                <span>
                  <!-- <i class="fa fa-plus" aria-hidden="true"></i> -->
                  Login
                </span>
              </a>
            </button>   
            {%endif%}
        </div>
        <!-- <div id="nav__btn_sell">SELL</div> -->
        <button id="nav__btn_sell" type="button" class='nav__btn'>
            <a href="{%url 'shop:AddProductView'%}" class="a_no_style">
              <span>
                <i class="fa fa-plus" aria-hidden="true"></i>
                <p>SELL</p>
              </span>
            </a>
        </button>
      </div>
    </nav>
    <!-- Bottom Nav -->
    <div id="bottom__nav__main">
      <a id="bottom__nav__drop" class="bottom__nav__text" href="#"
        >ALL CATEGORIES
        <i class="fa fa-angle-down" aria-hidden="true"></i>
      </a>
      <div id="bottom__nav__sub">
        <a class="bottom__nav__text" href="{%url 'core:CategoryView' category='TB'%}">Mobile Phones</a>
        <a class="bottom__nav__text" href="#">Cars</a>
        <a class="bottom__nav__text" href="#">Motorcycles</a>
        <a class="bottom__nav__text" href="#">Houses</a>
        <a class="bottom__nav__text" href="#">Tablets</a>
        <a class="bottom__nav__text" href="#">Computers</a>
      </div>
    </div>
    <!-- Header -->
    {%block header%}
      <header id="main__header" style="background-image: url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fesellercafe.com%2Fwp-content%2Fuploads%2F2020%2F04%2Fboost-brand-online-shopping-ecommerce.jpg&f=1&nofb=1);"></header>
    {%endblock%}

    <main id="main_content">
        {%block body%}
        {%endblock%}
    </main>

    <footer id="main__footer">
        <div id="upper__footer">
          <table>
            <tr>
              <th>POPULAR CATEGORIES</th>
              <th>TRENDING SEARCHES</th>
              <th>ABOUT US</th>
            </tr>
            <tr>
              <td>Cars</td>
              <td>Mobile Phones</td>
              <td>Contact US</td>
            </tr>
            <tr>
              <td>Computers</td>
              <td>Laptops</td>
              <td>About KST</td>
            </tr>
            <tr>
              <td>Houses</td>
              <td>Tablets</td>
              <td></td>
            </tr>
          </table>
    
          <table id="footer__follow_us">
            <tr>
              <th>Follow Us</th>
            </tr>
            <tr>
              <td>
                <i class="fa fa-facebook-square" aria-hidden="true"></i>
                <i class="fa fa-instagram" aria-hidden="true"></i>
                <i class="fa fa-twitter-square" aria-hidden="true"></i>
              </td>
            </tr>
          </table>
          <button type="button" class="watermark"><a href="https://www.instagram.com/its_aneeq_ak/" >Made by Aneeq</a></button>
        </div>
  
        <div id="bottom__footer">
          <p>Dated: 18/5/2021</p>
          <p>Copyright || aneeqakbqr@gmail.com</p>
        </div>
      </footer>
  </body>
  <script src="{%static 'js/base.js'%}"></script>
  <script src="{% static 'js/moment.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
  {% register_notify_callbacks callbacks='fill_notification_badge,notification_callback' %}
  
  {%block extraJS%}

  {%endblock%}
</html>

templates/category_list.html
{%extends 'home.html'%}
{%load static%}

{%block previousBlock%}

{%endblock%}

templates/generate_products.html
{%for product in products%}
    {%include '_product.html' with product=product%}
{%endfor%}

templates/payment_completed.html
<h1 style="color: greenyellow;">Payment Completed!</h1>
<p>Thanks for purchasing from us.</p>
<p>Take your receipt from <a href='{{receinpt_url}}'>here</a>.</p>

templates/product.html
{%extends 'base.html'%}
{%load static%}
{%block extraCSS%}
    <link rel="stylesheet" href="{%static 'css/product.css'%}" />
    <link rel="stylesheet" href="{%static 'css/product_detail.css'%}" />
    <link rel="stylesheet" href="{%static 'css/product_slideshow.css'%}" />
{%endblock%}
{%block header%}

{%endblock%}
{%block body%}
    <div id="product_detail_cont">

        <div id="product_detail_left">
            <div class="container">
                <div id="numbertext">0 / 0</div>
                {%for image_model in object.album.images.all%}
                    <div class="mySlides">
                        <img src={{image_model.image.url}} style="width:100%">
                    </div>
                {%endfor%}
                <!-- Next and previous buttons -->
                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>
                <!-- Thumbnail images -->
                <div class="row no_scroll">
                    {%for image_model in object.album.images.all%}
                    <div class="column">
                        <img class="demo cursor" src={{image_model.image.url}} style="width:100%" onclick="currentSlide(this)" alt="IMG">
                    </div>
                    {%endfor%}
                </div>
            </div>

            <div id="product_detail_description">
                <p class="product_detail_heading">Description:</p>
                <p class="product_detail_p">
                    {{object.description}}
                </p>
            </div>
        </div>


        <div id="product_detail_right">
            <div id="product_detail_details" class="product_detail_block">
                {%if product.discount_price%}
                    <p id="product_detail_block_price">$ <del>{{object.price}}</del> {{object.discount_price}}</p>
                {%else%}
                    <p id="product_detail_block_price">$ {{object.price}}</p>
                {%endif%}
                <p id="product_detail_block_name">{{object.name}}</p>
                <p id="product_detail_block_location">{{object.user.profile.address.country.name}},{{object.user.profile.address.get_province_display}},{{object.user.profile.address.city}}</p>
                <p id="product_detail_block_date">{{object.created_on}}</p>
            </div>
            <div id="product_detail_seller" class="product_detail_block">
                <p id="product_detail_seller_heading">Seller Description</p>
                <div id="product_detail_seller_avatar_cont">
                    <a href="{%url 'user:DetailUserView' pk=object.user.pk%}" class="a_no_style">
                        {%if object.user.profile.profile_pic%}
                        <div id="product_detail_seller_avatar" style="background-image:url({{object.user.profile.profile_pic.url}})"></div>
                        {%else%}
                        <div id="product_detail_seller_avatar" class="no_profile_pic"><span></span></div>
                        {%endif%}
                    </a>
                    <div id="product_detail_seller_user">
                        <div>
                            <p>{{object.user.username}}</p>
                            <p>{{object.user.date_joined.date}}</p>
                        </div>
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <div class="product_detail_block" style="text-align: center;">
                <a href={{object.get_add_to_cart_url}} class="addToCart_btn">Add To Cart</a>
            </div>
        </div>    
</div>
{%block extraJS%}
    <script src='{%static "js/product_detail.js"%}'></script>
{%endblock%}
{%endblock%}